#!/bin/sh

year=2020

if [ ! -d "../data/${year}/${year}nc" ]; then
  mkdir ../data/${year}/${year}nc
fi
#判断文件夹是否存在，如果不存在，那么创建它

nohup ./GRIB2_ExtractCoreVar0.py ${year} 0 > ${year}_0.log 2>&1 &

for hour in {3..57..6}
do
nohup ./GRIB2_ExtractCoreVar3.py ${year} ${hour} > ${year}_3.log 2>&1 &
done
nohup ./GRIB2_ExtractCoreVar3.py ${year} 57 > ${year}_57.log 2>&1

for hour in {63..117..6}
do
nohup ./GRIB2_ExtractCoreVar3.py ${year} ${hour} > ${year}_3.log 2>&1 &
done
nohup ./GRIB2_ExtractCoreVar3.py ${year} 117 > ${year}_117.log 2>&1

for hour in {123..177..6}
do
nohup ./GRIB2_ExtractCoreVar3.py ${year} ${hour} > ${year}_3.log 2>&1 &
done
nohup ./GRIB2_ExtractCoreVar3.py ${year} 177 > ${year}_177.log 2>&1


for hour in {6..60..6}
do
nohup ./GRIB2_ExtractCoreVar6.py ${year} ${hour} > ${year}_6.log 2>&1 &
done
nohup ./GRIB2_ExtractCoreVar6.py ${year} 60 > ${year}_60.log 2>&1

for hour in {66..120..6}
do
nohup ./GRIB2_ExtractCoreVar6.py ${year} ${hour} > ${year}_66.log 2>&1 &
done
nohup ./GRIB2_ExtractCoreVar6.py ${year} 120 > ${year}_120.log 2>&1

for hour in {126..180..6}
do
nohup ./GRIB2_ExtractCoreVar6.py ${year} ${hour} > ${year}_126.log 2>&1 &
done
nohup ./GRIB2_ExtractCoreVar6.py ${year} 180 > ${year}_180.log 2>&1

